name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd api
        npm install

    - name: Start API server
      run: |
        cd api
        npm start &
        sleep 5

    - name: Run tests
      run: |
        cd api
        npm test

    - name: Stop API server
      run: |
        npx kill-port 3000
